export enum CATEGORYTYPE {
  GRAM_ALTIN = 'GRAM ALTIN',
  SARRAFIYE_ESKI_TARIHLI = 'SARRAFIYE ESKI TARIHLI',
  ALTIN = 'ALTIN',
  GENEL = 'GENEL',
  PANO = 'PANO',
  PERAKENDE = 'PERAKENDE',
}
