export enum CATEGORYTYPE {
  'GRAM ALTIN' = 'GRAM ALTIN',
  'SARRAFIYE ESKI TARIHLI' = 'SARRAFIYE ESKI TARIHLI',
  ALTIN = 'ALTIN',
  GENEL = 'GENEL',
  PANO = 'PANO',
  PERAKENDE = 'PERAKENDE',
}
